on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - run: rustup update
    
    - run: cargo build --verbose

  clippy_check:
    name: Clippy Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - run: rustup update

      - run: rustup component add clippy

      - run: cargo clippy --workspace --all-targets --verbose --all-features

  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - run: rustup update

      - run: rustup component add rustfmt

      - run: cargo fmt --all -- --check

  code_coverage:
    name: Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: rustup update

      - run: rustup component add llvm-tools-preview

      - name: Download and install grcov
        run: |
          gh release download v0.8.13 -R github.com/mozilla/grcov  --pattern '*x86_64-unknown-linux-gnu.*' -O grcov.tar.bz2
          tar -xzf ./grcov.tar.bz2 -C $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run cargo test
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "cargo_test-%p-%m.profraw"
        run:
          cargo test

      - name: Run grcov
        run: grcov -h
